[project]
name = "faiss-builder"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "black>=25.1.0",
    "faiss",
    "matplotlib>=3.10.1",
    "pip>=25.0.1",
    "pytest>=8.3.5",
    "pytest-benchmark[histogram]>=5.1.0",
    "rich>=14.0.0",
    "ruff>=0.11.6",
]

[tool.pytest.ini_options]
log_cli = true
log_cli_level = "WARNING"
log_level = "WARNING"
