[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "${_FAISS_PACKAGE_NAME}"
requires-python = ">=3.13"
dynamic = ["description",
  "version",
  "readme",
  "license",
  "keywords",
  "authors",
  "dependencies"
]

[tool.setuptools.package-data]
"faiss" = ["*.so", "*.pyd"]
"faiss.contrib" = ["*.so", "*.so.12", "*.12", "*.2", "*.do.2", "*.pyd"]
